[package]
name = "winvd"
version = "0.0.47"
authors = ["Jari Otto Oskari Pennanen"]
license = "MIT"
edition = "2021"
description = "Provides functions for accessing Windows 11 virtual desktop API, requires at least 22621 build."
readme = "README-crate.md"
homepage = "https://github.com/ciantic/VirtualDesktopAccessor/tree/rust/"
repository = "https://github.com/ciantic/VirtualDesktopAccessor/tree/rust/"

[dependencies]
windows = { version = "0.57", features = ["implement", "Win32_System_Com", "Win32_UI_Shell_Common", "Win32_UI_WindowsAndMessaging", "Win32_Foundation", "Win32_System_Threading"] }
windows-core = "0.57"
windows-interface = "0.57"
windows-implement = "0.57"
crossbeam-channel = { version = "0.5", optional = true }
winit = { version = "0.30", optional = true }
macro_rules_attribute = "0.2"

[dev-dependencies]
once_cell = "1.5.0"

[lib]
name = "winvd"
path = "src/lib.rs"

[features]
integration-tests = []
multiple-windows-versions = [
    "windows/Win32_System_SystemInformation", # For RtlGetVersion return type
    "windows/Wdk_System_SystemServices",      # For RtlGetVersion
    "windows/Win32_System_Registry",          # For RegGetValueW
]

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"
all-features = true

[workspace]
members = ["testbin", "dll"] # , "examples/with-iced"]
